updated deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -138,7 +138,24 @@ jobs:
                 sleep 5
 
                 sudo systemctl status jw-registry --no-pager || true
-                curl -f http://localhost:8080/api/health || exit 1
+                
+                
+                sudo systemctl daemon-reload
+                sudo systemctl restart jw-registry
+
+                echo "Waiting for application to start..."
+
+              for i in {1..15}; do
+                if curl -f http://localhost:8080/api/health; then
+                echo "Application is UP!"
+                exit 0
+              fi
+            echo "Retrying... ($i)"
+            sleep 3
+            done
+
+            echo "Application failed to start!"
+            exit 1
               '
             "
           done
