updated deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -145,17 +145,16 @@ jobs:
 
                 echo "Waiting for application to start..."
 
-              for i in {1..15}; do
-                if curl -f http://localhost:8080/api/health; then
-                echo "Application is UP!"
-                exit 0
-              fi
-            echo "Retrying... ($i)"
-            sleep 3
-            done
-
-            echo "Application failed to start!"
-            exit 1
-              '
-            "
+              i=1
+          while [ $i -le 15 ]; do
+          if curl -f http://localhost:8080/api/health; then
+          echo "Application is UP!"
+          exit 0
+          fi
+          echo "Retrying... ($i)"
+          sleep 3
+          i=$((i+1))
           done
+
+          echo "Application failed to start!" 
+          exit 1
